#Welcome to the AlwaysOnline main configuration file!

#The delay to wait between checking to see if mojang is online, in seconds.
check-interval: 30

#Message for the MOTD to be when mojang servers are offline. Set to 'null' to disable.
message-motd-offline: '&eMojang servers are down,.newline.&ebut you can still connect!'

#The message to display when a user attempts to login while the mojang servers are offline, but their IP does not match.
message-kick-ip: 'We can not let you join since you are not on the same computer you logged on before!'

#The message to display when a user is new and logs in while mojang servers are offline.
message-kick-new: 'We can not let you join because the mojang servers are offline!'

#The message to display when a user attempts to login with an invalid minecraft username.
message-kick-invalid: 'Invalid username. Hacking?'

#The message to display when mojang servers go offline.
message-mojang-offline: '&5[&2AlwaysOnline&5]&a Mojang servers are now offline!'

#The message to display when mojang servers go back online.
message-mojang-online: '&5[&2AlwaysOnline&5]&a Mojang servers are now online!'

##########################################
#    Mysql Database Information
#    Only edit if using mysql
##########################################

use_mysql: false

host: '127.0.0.1'

port: 3306

database-name: 'server_database'

database-username: 'root'

database-password: 'password'

#Please do not change this!
config_version: 5